//
// Created by Tom on 2026/3/13.
//

#ifndef SHMIPCC_SHMSERVERCONFIG_H
#define SHMIPCC_SHMSERVERCONFIG_H

#define SHM_SERVER_MAX_UDS_PROTOCOL_FD 10
#define SHM_SERVER_MAX_PROGRESS_COUNT 2
#define SHM_SERVER_PROTOCOL_HEAD_SIZE 7

#define SHM_SERVER_DEFAULT_NAME "shmIpc"

#endif //SHMIPCC_SHMSERVERCONFIG_H
